service: public-holiday-api

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: ap-northeast-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
        - "s3:GetObject"
        - "s3:PutObject"
        - "s3:DeleteObject"
      Resource:
        Fn::Join:
          - ""
          - - "arn:aws:s3:::"
            - !Ref CsvBucketName
            - "/*"
  environment:
    holiday_csv_url: 'https://www8.cao.go.jp/chosei/shukujitsu/syukujitsu.csv'
    csv_bucket_name: !Ref CsvBucketName
    csv_bucket_expiration_in_days: ${opt:bucket-expiration-in-days, '1'}
    TZ: 'Asia/Tokyo'

package:
  exclude:
    - README.md

layers:
  publicHolidayApi:
    path: layer

functions:
  search:
    handler: handler.search
    layers:
      - {Ref: PublicHolidayApiLambdaLayer}
    events:
      - http:
          path: holiday
          method: get
          integration: lambda
          request:
            template:
              application/json: '{ "date" : "" }'
      - http:
          path: holiday/{date}
          method: get
          integration: lambda
          request:
            template:
              application/json: '{ "date" : "$input.params(''date'')" }'
resources:
  Resources:
    CsvBucketName:
      Type: AWS::S3::Bucket
      Properties:
        LifecycleConfiguration:
          Rules:
          - Status: Enabled
            ExpirationInDays: ${self:provider.environment.csv_bucket_expiration_in_days}
            NoncurrentVersionExpirationInDays: 1
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 1
