service: public-holiday-api

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
  region: ap-northeast-1
  environment:
    holiday_csv_url: 'https://www8.cao.go.jp/chosei/shukujitsu/syukujitsu.csv'
    TZ: 'Asia/Tokyo'

package:
  exclude:
    - README.md

layers:
  publicHolidayApi:
    path: layer

functions:
  search:
    handler: handler.search
    layers:
      - {Ref: PublicHolidayApiLambdaLayer}
    events:
      - http:
          path: holiday
          method: get
          integration: lambda
          request:
            template:
              application/json: '{ "date" : "" }'
      - http:
          path: holiday/{date}
          method: get
          integration: lambda
          request:
            template:
              application/json: '{ "date" : "$input.params(''date'')" }'
